[package]
name = "qpage"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
reqwest = { version = "0.12.7", features = ["blocking"] }
zip = "2.2.0"
flate2 = "1.0.33"
tar = "0.4.42"
scraper = "0.20.0"
